pip install colorama
pip install faker
pip install tqdm
pip install tkinter
pip install requests
pip install sniffio=1.3.0
pip install attrs==22.2.0
pip install flask==2.2.2
pip install httpx==0.23.3
pip install py-cord
pip install typing_extensions==4.4.0
pip install scapy
pip install beautifulsoup4
pip install discord-webhook
